[tool.flakeheaven]
exclude = [
    ".tox",
    ".venv",
    ".egg",
    "build",
    "client",
    "dist",
    "docs",
    "var",
    "venv",
]
max_line_length = 88

[tool.flakeheaven.exceptions."**/__init__.py"]
pyflakes = ["-F401"] # __init__ files can have imports just to allow "shortcuts"

[tool.flakeheaven.plugins]
pycodestyle = ["+*", "-W503", "-W504", "-W605"]
pyflakes = ["+*"]
"flake8-*" = ["+*", "-Q000"]
mccabe = ["+*"]
pylint = [
    "+*",
    "-C0301", # line-too-long -> already covered by flake E501 
    "-C0411", # wrong-import-order - this will be handled by isort
    "-F6401", # cannot-enumerate-pytest-fixtures
    "-R0903", # too-few-public-methods - we don't necessarily see this as a bad thing
]
